### PR TITLE
Documentation Improvement, User Interface added, Shortcuts for usability added. 

### PR DESCRIPTION
**Pull request by mauroalejandrojm**
Greetings

* This update adds a popup user interface with a minimalistic design.
* Additionally, I added two shortcuts based on usability like my projects redirect and Overleaf API request to create blank projects.
* The toggle lets you activate the "split window view" (we need a name to properly address the functionality to users).
* The toggle is restricted to work with the overleaf project domain, so it won't work on other websites.
* Icon colour change to reflect the status of the toggle to the users.
* The shortcuts aren't restricted and they can be used from "any website'', except new tabs. 
* The previous glitch was found using Edge (please tell me if it works in Chrome).
* Images added to README file to show the use cases in a friendly way.
* Troubleshooting section added to the README file.
* I noticed some rate limits in the PDF build, but it still renders the PDF after a few seconds.
* Also, I noticed some not found in the PDF build, but it still renders the PDF after a few seconds. 
* The shortcut buttons don't work in a new tab, probably because it doesn't inject javascript, but this could be a problem related to Edge itself or the manifest version 2.

### CODE REVIEW

**Comment by shreyashankar** [comment]
Wow awesome! Could you resolve conflicts? Then I'll take a look :)

**Comment by mauroalejandrojm** [comment]
I have fixed the brach issues, now you can review my pull request. 

I have updated the previous description.

**Comment by mauroalejandrojm** [comment]
What's the plan to publish it to google chrome? 
I have already published it to Microsoft Edge with your License of course, but I'm waiting for the review of this version with the icon status changes.

**Comment by shreyashankar** [comment]
Sorry I was traveling -- I'm looking at this today!

**Review by shreyashankar — APPROVED** [review]
Just tested -- works great on my computer! Will add to chrome extensions this week :)

**Comment by mauroalejandrojm** [comment]
Great, I will add a background process to improve the toggle status check and a try catch to improve the toggle use.

But I'll do it next month.

**Pull request merged**
